### ISSUE TITLE
L1 Tokenomics: Fix commands

### ISSUE THREAD

**Issue by owenwahlgren** [ava-labs/avalanche-academy#207]
Paths have updated for contracts:
https://academy.avax.network/course/l1-tokenomics/03-multi-chain-ecosystems/03-use-erc20-as-native-token#deploy-an-erc-20-contract-on-c-chain

Update paths / use alternative deployment methods where seen fit

**Comment by Andyvargtz** [comment]
Instructions fixed in Academy PR: https://github.com/ava-labs/avalanche-starter-kit/commit/5b598cd7d490f19460b309d659c867d33598b6e1
Remapping added in Commit to Starter-kit: https://github.com/ava-labs/avalanche-starter-kit/commit/5b598cd7d490f19460b309d659c867d33598b6e1
